apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -staging              # nginx-demo-staging, whoami-staging

patches:
  - patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: nginx-demo
        namespace: argocd
      spec:
        source:
          path: 8-argocd-app-of-apps/workloads/nginx/overlays/staging
        destination:
          namespace: nginx-staging
  - patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: whoami
        namespace: argocd
      spec:
        source:
          path: 8-argocd-app-of-apps/workloads/whoami/overlays/staging
        destination:
          namespace: whoami-staging
