apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: whoami-staging

replicas:
  - name: whoami
    count: 1

patches:
  - target:
      kind: Ingress
      name: whoami
    patch: |-
      - op: add
        path: /spec/rules/0/host
        value: whoami.staging.k8s-demo.locl
